import 'package:flutter/foundation.dart';

class Inspection_model {
  int? year;
  int? division_id;
  int? district_id;
  int? thana_id;
  int? institute_type;
  int? institute_id;
  String? eiinNumber;
  String? inspectorName;
  String? approval_date;
  String? mpo_date;
  String? inspectorPost;
  String? inspectorMobile;
  String? inspectorEmail;
  String? inspectionDate;
  String? headmaster_name;
  String? headmaster_mobile_no;
  String? institute_permited_post;
  String? headmaster_post;
  String? total_teachers;
  String? total_women_teachers;
  String? total_songjukto_teachers;
  String? present_teacher;
  String? abcent_teacher;
  int? isFormalDress;
  int? isIctTraining;
  int? isOtherTraining;
  String? empty_post;
  String? total_students;
  String? total_girls_students;
  String? total_examine;
  String? overall_status;
  String? cocurricular_activities;
  String? total_passed;
  String? special_needs_students;
  String? cholarship_students;
  String? dakhilExamine_students;
  String? alimExamine_students;
  String? fazilExamine_students;
  String? kamilExamine_students;
  String? vokExamine_students;
  String? bmetExamine_students;
  String? deplomaEngExamine_students;
  String? shortExamine_students;

  String? dakhilPass_students;
  String? alimPass_students;
  String? fazilPass_students;
  String? kamilPass_students;
  String? vokPass_students;
  String? bmetPass_students;
  String? deplomaEngPass_students;
  String? shortPass_students;

  String? recognise_date;
  int? electricity_facility;
  int? internet_facility;
  String? total_multimedia_classroom;
  String? total_digital_lab;
  int? isSkrLab;
  int? isOnlineClass;
  int? isCleanness;
  int? isCachmant;
  int? isRegisok;
  int? isWeekWork;
  int? isPrymariHealth;
  String? guardian_gathering;
  String? toiletClean;
  String? safeWater;
  String? tree;
  String? cleanDress;
  String? mentalHealthActivity;
  String? covid19_vaccinated;
  String? weak_student;
  String? soft_skill;
  String? co_caricolum;
  String? yearlyPlan;
  String? shreniKarjo;
  String? upgradationSuggession;
  String? previousInspetion;
  String? previousInspetionApply;
  String? comments;
  String? week_studuents_activities;



}